plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.philipsremote'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.philipsremote'
        minSdk 23
        targetSdk 35
        versionCode 25
        versionName '1.3.6'
    }

    signingConfigs {
        release {
            def storeFilePath = System.getenv("KEYSTORE_FILE")
            if (storeFilePath) {
                storeFile file(storeFilePath)
            }
            storePassword System.getenv("KEYSTORE_PASSWORD")
            keyAlias System.getenv("KEY_ALIAS")
            keyPassword System.getenv("KEY_PASSWORD")
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
}
